version: '3.8'

services:
  mexc-sniper:
    build:
      context: ./backend-rust
      dockerfile: Dockerfile
    network_mode: "host"
    restart: always
    environment:
      - USE_SSM=true
      - DYNAMODB_TABLE=MexcSniperOrders
      - RUST_LOG=info
